# Generated by Django 4.1.4 on 2023-08-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.CharField(max_length=200)),
                ('color_logo', models.ImageField(upload_to='logos', verbose_name='Color Logo (170*55)')),
                ('white_logo', models.ImageField(upload_to='logos', verbose_name='White Logo (170*55)')),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('opening_hours', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '01. Company Setup',
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.CharField(max_length=200)),
                ('header_text', models.TextField()),
                ('header_image', models.ImageField(upload_to='home_images/', verbose_name='Header Image (585*335)')),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
            ],
            options={
                'verbose_name_plural': '02.Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images', verbose_name='Image (1920*1080)')),
                ('heading_text', models.CharField(max_length=200)),
                ('sub_heading_text', models.CharField(max_length=200)),
                ('button_text', models.CharField(max_length=50)),
                ('button_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': '04. Slider',
            },
        ),
    ]
