# Generated by Django 4.1.4 on 2023-08-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_contact_alter_partner_image_alter_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.CharField(max_length=200)),
                ('heading_image', models.ImageField(upload_to='join_images/', verbose_name='Heading Image (1920*800)')),
                ('court_image', models.ImageField(upload_to='join_images/', verbose_name='Heading Image (1920*800)')),
                ('booking_details1', models.TextField()),
                ('booking_details2', models.TextField()),
                ('bottom_text', models.TextField()),
            ],
            options={
                'verbose_name_plural': '06. Join RCS Page Content',
            },
        ),
    ]
