# Generated by Django 4.1.4 on 2023-08-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_gallery_alter_joinrcs_court_image_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('court_image', models.ImageField(upload_to='join_images/', verbose_name='Court Image (570*400)')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': '06. Participation and Honours',
            },
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery_images/', verbose_name='Heading Image (370*307)'),
        ),
    ]
