# Generated by Django 4.1.4 on 2023-08-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_participation_alter_galleryimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='join_images/', verbose_name='Featured Image (954*774)')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': '06. Events',
            },
        ),
        migrations.AlterField(
            model_name='participation',
            name='court_image',
            field=models.ImageField(upload_to='join_images/', verbose_name='Featured Image (570*400)'),
        ),
    ]
