# Generated by Django 4.1.4 on 2023-08-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_event_alter_participation_court_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '03. Banner Image'},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='heading_text',
        ),
    ]
