# Generated by Django 4.1.4 on 2023-08-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_alter_slider_options_remove_slider_button_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': '04. Blogs'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '07. Contact'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': '11. Events'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': '10. Gallery'},
        ),
        migrations.AlterModelOptions(
            name='joinrcs',
            options={'verbose_name_plural': '08. Join RCS Page Content'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name_plural': '09. Participation and Honours'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name_plural': '05. Testimonials'},
        ),
    ]
