# Generated by Django 4.1.4 on 2023-08-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_alter_blog_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='slider_images/mobile', verbose_name='Image (450*750)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider_images/desktop', verbose_name='Image (1920*1080)'),
        ),
    ]
