# Generated by Django 4.1.4 on 2023-08-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_slider_mobile_image_alter_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='mobile_image',
            field=models.ImageField(upload_to='slider_images/mobile', verbose_name='Mobile Image (450*750)'),
        ),
    ]
