# Generated by Django 4.1.4 on 2023-08-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0014_alter_slider_mobile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
