# Generated by Django 4.1.4 on 2023-08-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0015_testimonial_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
